app:
    resource: @AppBundle/Controller/
    prefix: /admin
    type:     annotation

api:
    resource: @AppBundle/Api
    type:     annotation
    prefix: /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"