parameters:
    app.data.class: AppBundle\Entity\Data

services:
    app.chart.processor.doctrine:
        class: AppBundle\Chart\Data\DoctrineDataProcessor
        arguments:
            - @doctrine.orm.entity_manager
            - %app.data.class%
        tags:
            - { name: app.chart.data.processor }

    app.chart.data.doctrine_collection:
        class: AppBundle\Chart\Data\DoctrineDataCollection

    app.indicator.factory:
        class: AppBundle\Indikator\IndikatorFactory
        arguments:
            - @doctrine.orm.entity_manager

    app.wilayah.factory:
        class: AppBundle\Wilayah\WilayahFactory
        arguments:
            - @doctrine.orm.entity_manager

    app.regional.factory:
        class: AppBundle\Regional\RegionalFactory
        arguments:
            - @doctrine.orm.entity_manager

    app.security.encoder.generator:
        class: AppBundle\Security\Encoder\BaseGenerator

    app.security.encoder.password:
        class: AppBundle\Security\Encoder\PasswordEncoder
        arguments:
            - @app.security.encoder.generator