<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionalRepository extends EntityRepository implements SearchableInterface
{
    public function findByKeyword($keyword)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->andWhere($qb->expr()->like('a.name', $qb->expr()->literal('%'.$keyword.'%')));

        return $qb->getQuery()->getResult();
    }
}
